language: ruby
cache: bundler

services:
  - postgresql

install:
  - bundle install

before_script:
  - psql -c 'create database "pronosticos_dashboard-test";' -U postgres
  - bundle exec rake db:setup

script:
  - bundle exec rspec
